# Generated by Django 6.0.1 on 2026-01-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('brand', models.CharField(choices=[('kitchen', 'The Cafe'), ('dadho', 'Dadho Sutho'), ('zabardast', 'Zabardast')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('guests', models.IntegerField()),
                ('table_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Confirmed', max_length=20)),
            ],
        ),
    ]
