# Generated by Django 6.0.1 on 2026-01-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('ramen', 'Ramen'), ('fries', 'Fries'), ('burger', 'Burgers'), ('appetizers', 'Appetizers'), ('pasta', 'Pasta'), ('dumplings', 'Dumplings'), ('sizzlers', 'Sizzlers'), ('rice', 'Rice'), ('noodles', 'Noodles'), ('baos', 'Baos'), ('dessert', 'Dessert'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
