# Generated by Django 6.0.1 on 2026-01-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('ramen', 'Ramen'), ('fries', 'Fries'), ('burger', 'Burgers'), ('appetizers', 'Appetizers'), ('pasta', 'Pasta'), ('dumplings', 'Dumplings'), ('sizzlers', 'Sizzlers'), ('rice', 'Rice'), ('noodles', 'Noodles'), ('baos', 'Baos'), ('dessert', 'Dessert'), ('salad', 'Salads'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, default='https://source.unsplash.com/random/food'),
        ),
    ]
